backend:
  name: git-gateway
  branch: develop

media_folder: static/img
public_folder: /img

collections:
  - name: "index"
    label: "Index"
    files:
      - file: "src/pages/index/index.md"
        label: "Index"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index"}
          - {label: "Path", name: "path", widget: "hidden", default: "/"}
          - {label: Hero, name: hero, widget: object, fields:
              [
                {label: "Hero Title", name: "title", widget: "string"},
                {label: "Hero Description", name: "description", widget: "markdown"}
              ]
            }
          - {label: About, name: about, widget: object, fields:
              [
                {label: "About Title", name: "title", widget: "string"},
                {label: "About Description Col 1", name: "col_1", widget: object, fields:
                  [
                    {label: "Title", name: "title", widget: "string"},
                    {label: "Description", name: "description", widget: "markdown"}
                  ]
                },
                {label: "About Description Col 2", name: "col_2", widget: object, fields:
                  [
                    {label: "Title", name: "title", widget: "string"},
                    {label: "Description", name: "description", widget: "markdown"}
                  ]
                }
              ]
            }
          - {label: Location, name: loc, widget: object, fields:
              [
                {label: "Location Title", name: "title", widget: "string"},
                {label: "Location Description", name: "description", widget: "markdown"},
                {label: "Location Marker", name: "marker", widget: "markdown"},
                {label: "Location Coords", name: "coords", widget: object, fields:
                  [
                    {label: "Latitude", name: "lat", widget: "number"},
                    {label: "Longitude", name: "lng", widget: "number"}
                  ]
                }
              ]
          }
          - {label: Sponsors, name: sponsors, widget: object, fields:
            [
              {label: "Sponsors Title", name: "title", widget: "string"},
              {label: "Sponsors Description", name: "description", widget: "markdown"},
              {label: "Sponsors List", name: "sponsor_list", widget: "object", fields:
                [
                  {label: "Image Field 1", name: "img1", widget: "image", default: "/img/partners/gdg_reading.jpeg"},
                  {label: "Image Field 2", name: "img2", widget: "image", default: "/img/partners/gdg_reading.jpeg"},
                  {label: "Image Field 3", name: "img3", widget: "image", default: "/img/partners/gdg_reading.jpeg"},
                  {label: "Image Field 4", name: "img4", widget: "image", default: "/img/partners/gdg_reading.jpeg"},
                  {label: "Image Field 5", name: "img5", widget: "image", default: "/img/partners/gdg_reading.jpeg"},
                  {label: "Image Field 6", name: "img6", widget: "image", default: "/img/partners/gdg_reading.jpeg"},
                  {label: "Image Field 7", name: "img7", widget: "image", default: "/img/partners/gdg_reading.jpeg"},
                  {label: "Image Field 8", name: "img8", widget: "image", default: "/img/partners/gdg_reading.jpeg"},
                ]
              }
            ]
          }
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
